name: web deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v14


      - name: cloning repo
        uses: actions/checkout@v4

      - name: download rom
        run: wget https://github.com/cbeust/space-invade.rs/raw/refs/heads/main/space-invaders.rom

      - name: building for web
        run: PLATFORM=WEB make web-release

      - name: setup pages
        uses: actions/configure-pages@v3

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./pub"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name : deploy to github pages
        uses: actions/deploy-pages@v2
